### ISSUE TITLE
discussion: support yml format

### ISSUE THREAD

**Issue by fraserxu** [freeman-lab/minidocs#38]
Currently it supports to define the nav in a JavaScript object

```js
var contents = {
  'overview': {
    'about': 'about.md'
  },
  'animals': {
    'furry': {
      'sheep': 'sheep.md'
    },
    'pink': {
      'pig': 'pig.md'
    }
  }
}
```

If it can support yml, it will be

```yml
---
  overview: 
    about: "about.md"
  animals: 
    furry: 
      sheep: "sheep.md"
    pink: 
      pig: "pig.md"
```

The advantage of using `yml` is when the navigation becomes big, it will become much easier to read and write compare to `json`, but the downside it's we need to include a library to parse yml file.

What do you think?

**Comment by yoshuawuyts** [comment]
Haha, I reckon JSON is good enough; but if we're going to put fave file formats out there for me `.toml` trumps `.yml` in terms of legibility and whitespace mangling hah:
```toml
[overview]
about = "about.md"

[animals]
  [animals.furry]
    sheep = "sheep.md"
  [animals.pink]
    pig = "pig.md"
```
